Name: vegastrike-data
Summary: Vegastrike - a free 3D space fight simulator (data files)
Version: 0.1.0
Release: 1
Copyright: GPL
Group: X11/GL/Games
Source: http://prdownloads.sourceforge.net/vegastrike/vegastrike-data-0.1.0.tar.gz
Packager: Daniel Horn <danielhorn@mindspring.com>
BuildRoot: /tmp/vegastrike
Prefix: /usr/local

%description
Vegastrike is a free 3D space fight simulator under the GPL

Vega Strike is an Interactive Flight Simulator/Real Time Stratagy being
 developed for Linux and Windows in 3d OpenGL...

this archive contains the data files necessary to play Vegastrike.

%prep
rm -rf $RPM_BUILD_ROOT
%setup -n vegastrike-data-0.1.0

%build
echo "nothing to build"

%install
echo installing to $RPM_BUILD_ROOT
mkdir $RPM_BUILD_ROOT/data
cp -a * $RPM_BUILD_ROOT/data


%clean
rm -rf $RPM_BUILD_ROOT

%files
%{prefix}/games/vegastrike/bin/vegastrike
%{prefix}/games/vegastrike/objconv/3ds2xml
%{prefix}/games/vegastrike/objconv/obj2xml
%{prefix}/games/vegastrike/objconv/wcp2xml

%{prefix}/games/vegastrike/data/ai/events/default.scared.xml
%{prefix}/games/vegastrike/data/ai/events/default.agg.xml
%{prefix}/games/vegastrike/data/ai/events/defaultscared1.xml
%{prefix}/games/vegastrike/data/ai/events/default.int.xml
%{prefix}/games/vegastrike/data/ai/events/default.final.xml
%{prefix}/games/vegastrike/data/ai/events/Makefile.am
%{prefix}/games/vegastrike/data/ai/events/default.test.xml
%{prefix}/games/vegastrike/data/ai/events/default.agg.stupid
%{prefix}/games/vegastrike/data/ai/Makefile.am
%{prefix}/games/vegastrike/data/ai/script/leech.xai
%{prefix}/games/vegastrike/data/ai/script/teststupid.xml
%{prefix}/games/vegastrike/data/ai/script/afterburnerslide.xml
%{prefix}/games/vegastrike/data/ai/script/afterburn-turntowards.xml
%{prefix}/games/vegastrike/data/ai/script/friendorfoe.xai
%{prefix}/games/vegastrike/data/ai/script/aitest.xml
%{prefix}/games/vegastrike/data/ai/script/skilledabslide.xml
%{prefix}/games/vegastrike/data/ai/script/afterburn-turntowards-itts.xml
%{prefix}/games/vegastrike/data/ai/script/cloak.xml
%{prefix}/games/vegastrike/data/ai/script/Makefile.am
%{prefix}/games/vegastrike/data/ai/script/shelton-slide.xml
%{prefix}/games/vegastrike/data/ai/script/turntowards.xml
%{prefix}/games/vegastrike/data/ai/script/dumbfire.xai
%{prefix}/games/vegastrike/data/ai/script/evade.xml
%{prefix}/games/vegastrike/data/ai/script/kickstop.xml
%{prefix}/games/vegastrike/data/ai/script/heatseek.xai
%{prefix}/games/vegastrike/data/ai/script/stop.xml
%{prefix}/games/vegastrike/data/ai/script/turnaway.xml
%{prefix}/games/vegastrike/data/ai/script/turntowardsitts.xml
%{prefix}/games/vegastrike/data/ai/script/imrec.xai
%{prefix}/games/vegastrike/data/test5.mission
%{prefix}/games/vegastrike/data/linux.config
%{prefix}/games/vegastrike/data/Makefile
%{prefix}/games/vegastrike/data/install.bat
%{prefix}/games/vegastrike/data/testmission.txt
%{prefix}/games/vegastrike/data/units/aeon/aeon
%{prefix}/games/vegastrike/data/units/aeon/aeon.xmesh
%{prefix}/games/vegastrike/data/units/aeon/aeon.bmp
%{prefix}/games/vegastrike/data/units/aeon/aeon.bsp
%{prefix}/games/vegastrike/data/units/kyta/kyta
%{prefix}/games/vegastrike/data/units/kyta/kyta.xmesh
%{prefix}/games/vegastrike/data/units/nova/nova
%{prefix}/games/vegastrike/data/units/nova/nova.bmp
%{prefix}/games/vegastrike/data/units/nova/nova.xmesh
%{prefix}/games/vegastrike/data/units/tian/tian
%{prefix}/games/vegastrike/data/units/tian/scout.bmp
%{prefix}/games/vegastrike/data/units/tian/tian.xmesh
%{prefix}/games/vegastrike/data/units/tian/tian.bsp
%{prefix}/games/vegastrike/data/units/merchant/Makefile.am
%{prefix}/games/vegastrike/data/units/destiny/destiny
%{prefix}/games/vegastrike/data/units/destiny/destiny.bmp
%{prefix}/games/vegastrike/data/units/destiny/destiny.xmesh
%{prefix}/games/vegastrike/data/units/cruiser/cruiser
%{prefix}/games/vegastrike/data/units/cruiser/cruiser.xmesh
%{prefix}/games/vegastrike/data/units/cruiser/cruiser.bmp
%{prefix}/games/vegastrike/data/units/cruiser/cruiser.bsp
%{prefix}/games/vegastrike/data/units/turretgunsmall/turretgunsmall
%{prefix}/games/vegastrike/data/units/turretgunsmall/turretgunsmall.xmesh
%{prefix}/games/vegastrike/data/units/imrec/imrec
%{prefix}/games/vegastrike/data/units/imrec/imrec.xmesh
%{prefix}/games/vegastrike/data/units/leech/leech.xmesh
%{prefix}/games/vegastrike/data/units/leech/leech
%{prefix}/games/vegastrike/data/units/lekra/lekra
%{prefix}/games/vegastrike/data/units/lekra/lekra.xmesh
%{prefix}/games/vegastrike/data/units/retro/Makefile.am
%{prefix}/games/vegastrike/data/units/ConfedHq/ConfedHq
%{prefix}/games/vegastrike/data/units/ConfedHq/ConfedHq1.xmesh
%{prefix}/games/vegastrike/data/units/ConfedHq/ConfedHq2.xmesh
%{prefix}/games/vegastrike/data/units/ConfedHq/hull1.bmp
%{prefix}/games/vegastrike/data/units/ConfedHq/hull2.bmp
%{prefix}/games/vegastrike/data/units/ConfedHq/Makefile.am
%{prefix}/games/vegastrike/data/units/drydock/drydock-Cube_27-Material1.xmesh
%{prefix}/games/vegastrike/data/units/drydock/drydock
%{prefix}/games/vegastrike/data/units/drydock/Makefile.am
%{prefix}/games/vegastrike/data/units/drydock/drydock-Cube_27-Material.xmesh
%{prefix}/games/vegastrike/data/units/drydock/Capwin~2.bmp
%{prefix}/games/vegastrike/data/units/drydock/drydock.bsp
%{prefix}/games/vegastrike/data/units/turretgun/turretgunsmall
%{prefix}/games/vegastrike/data/units/turretgun/turretgun
%{prefix}/games/vegastrike/data/units/turretgun/turretgun.xmesh
%{prefix}/games/vegastrike/data/units/turretgun/turretgunsmall.xmesh
%{prefix}/games/vegastrike/data/units/turretgun/turretgun.bsp
%{prefix}/games/vegastrike/data/units/firefly/firefly.xmesh
%{prefix}/games/vegastrike/data/units/firefly/firefly
%{prefix}/games/vegastrike/data/units/firefly/firefly.bmp
%{prefix}/games/vegastrike/data/units/militia/Makefile.am
%{prefix}/games/vegastrike/data/units/aevant/aevant
%{prefix}/games/vegastrike/data/units/aevant/aevant.bmp
%{prefix}/games/vegastrike/data/units/aevant/aevant.xmesh
%{prefix}/games/vegastrike/data/units/aevant/aevant.bsp
%{prefix}/games/vegastrike/data/units/station/.#station.xmesh.1.1
%{prefix}/games/vegastrike/data/units/station/station.xmesh
%{prefix}/games/vegastrike/data/units/station/station.nobsp.xmesh
%{prefix}/games/vegastrike/data/units/station/station
%{prefix}/games/vegastrike/data/units/station/station.C
%{prefix}/games/vegastrike/data/units/station/station.bmp
%{prefix}/games/vegastrike/data/units/station/station.bsp
%{prefix}/games/vegastrike/data/units/dagger/dagger.xmesh
%{prefix}/games/vegastrike/data/units/dagger/dagger
%{prefix}/games/vegastrike/data/units/dagger/dagger.bmp
%{prefix}/games/vegastrike/data/units/confed/Makefile.am
%{prefix}/games/vegastrike/data/units/Makefile.am
%{prefix}/games/vegastrike/data/units/osprey/osprey.xmesh
%{prefix}/games/vegastrike/data/units/osprey/osprey
%{prefix}/games/vegastrike/data/units/osprey/osprey.bmp
%{prefix}/games/vegastrike/data/units/turret/turret.xmesh
%{prefix}/games/vegastrike/data/units/turret/turretsmall.xmesh
%{prefix}/games/vegastrike/data/units/turret/turret
%{prefix}/games/vegastrike/data/units/turret/turretsmall
%{prefix}/games/vegastrike/data/units/turret/turret.bsp
%{prefix}/games/vegastrike/data/units/heatseek/heatseek.xmesh
%{prefix}/games/vegastrike/data/units/heatseek/heatseek
%{prefix}/games/vegastrike/data/units/turretsmall/turretsmall.xmesh
%{prefix}/games/vegastrike/data/units/turretsmall/turret
%{prefix}/games/vegastrike/data/units/turretsmall/turretsmall
%{prefix}/games/vegastrike/data/units/carrier/carrier.xmesh
%{prefix}/games/vegastrike/data/units/carrier/carrier.xmesh.bak
%{prefix}/games/vegastrike/data/units/carrier/carrier.bak
%{prefix}/games/vegastrike/data/units/carrier/carrier.bmp
%{prefix}/games/vegastrike/data/units/carrier/carrier
%{prefix}/games/vegastrike/data/units/planetary-ring/Makefile.am
%{prefix}/games/vegastrike/data/units/planetary-ring/Planetary-Ring.xmesh
%{prefix}/games/vegastrike/data/units/planetary-ring/planetary-ring
%{prefix}/games/vegastrike/data/units/planetary-ring/planetary-ring_shield.bsp
%{prefix}/games/vegastrike/data/units/planetary-ring/planetary-ring.bsp
%{prefix}/games/vegastrike/data/units/dumbfire/dumbfire.xmesh
%{prefix}/games/vegastrike/data/units/dumbfire/Makefile.am
%{prefix}/games/vegastrike/data/units/dumbfire/dumbfire
%{prefix}/games/vegastrike/data/units/headhunter/Headhntr.bmp
%{prefix}/games/vegastrike/data/units/headhunter/headhunter.xmesh
%{prefix}/games/vegastrike/data/units/headhunter/headhunter
%{prefix}/games/vegastrike/data/units/friendorfoe/friendorfoe.xmesh
%{prefix}/games/vegastrike/data/units/friendorfoe/friendorfoe
%{prefix}/games/vegastrike/data/red05_sphere.bmp
%{prefix}/games/vegastrike/data/blank.system
%{prefix}/games/vegastrike/data/readme
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/eject.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/eject.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/eject.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/disabled-cockpit.cpt
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/auto.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/auto.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/auto.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/crosshairs.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/rvdu.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/blasterpower.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/blasterpower.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/blasterpower.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/Makefile.am
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/shieldf.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/shieldf.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/shieldf.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/armorf.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/armorf.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/armorl.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/armorl.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/armorl.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/locklight.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/locklight.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/locklight.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/lvdu.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/fuelstat.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/fuelstat.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/fuelstat.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/generic.spr
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/9x12.font
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/radar.alp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/radar.bmp
%{prefix}/games/vegastrike/data/disabled-cockpit.cpt/radar.spr
%{prefix}/games/vegastrike/data/geforce2.config
%{prefix}/games/vegastrike/data/glut32.dll
%{prefix}/games/vegastrike/data/fiction
%{prefix}/games/vegastrike/data/sol.system
%{prefix}/games/vegastrike/data/animations/locationselect.ani/locationselect.alp
%{prefix}/games/vegastrike/data/animations/locationselect.ani/locationselect.ani
%{prefix}/games/vegastrike/data/animations/locationselect.ani/locationselect.bmp
%{prefix}/games/vegastrike/data/animations/locationselect.ani/Makefile.am
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a01.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a01.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a02.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a02.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a03.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a03.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a04.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a04.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a05.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a05.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a06.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a06.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a07.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a07.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a08.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a08.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a09.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a09.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a10.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a10.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a11.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a11.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a12.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a12.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a13.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a13.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a14.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a14.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a15.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a15.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a16.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a16.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a17.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a17.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a18.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a18.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a19.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a19.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a20.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a20.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a21.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a21.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a22.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a22.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a23.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a23.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a24.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a24.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a25.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a25.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a26.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a26.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a27.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a27.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a28.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a28.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a29.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a29.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a30.alp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/realexplode2a30.bmp
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/explosion_orange.ani
%{prefix}/games/vegastrike/data/animations/explosion_orange.ani/Makefile.am
%{prefix}/games/vegastrike/data/animations/Makefile.am
%{prefix}/games/vegastrike/data/animations/locationselect_up.ani/Makefile.am
%{prefix}/games/vegastrike/data/animations/locationselect_up.ani/locationselect_up.alp
%{prefix}/games/vegastrike/data/animations/locationselect_up.ani/locationselect_up.ani
%{prefix}/games/vegastrike/data/animations/locationselect_up.ani/locationselect_up.bmp
%{prefix}/games/vegastrike/data/animations/mass_driver.ani/mass_driver.alp
%{prefix}/games/vegastrike/data/animations/mass_driver.ani/mass_driver.ani
%{prefix}/games/vegastrike/data/animations/mass_driver.ani/mass_driver.bmp
%{prefix}/games/vegastrike/data/test2.mission
%{prefix}/games/vegastrike/data/panic.m3u
%{prefix}/games/vegastrike/data/sprites/mouse.alp
%{prefix}/games/vegastrike/data/sprites/mouse.bmp
%{prefix}/games/vegastrike/data/sprites/mouse.spr
%{prefix}/games/vegastrike/data/sprites/selectbox.alp
%{prefix}/games/vegastrike/data/sprites/selectbox.bmp
%{prefix}/games/vegastrike/data/sprites/selectbox.spr
%{prefix}/games/vegastrike/data/sprites/Makefile.am
%{prefix}/games/vegastrike/data/textures/TerranPriA.bmp
%{prefix}/games/vegastrike/data/textures/mercury.bmp
%{prefix}/games/vegastrike/data/textures/particletexture.bmp
%{prefix}/games/vegastrike/data/textures/KilrathiPriRGB.bmp
%{prefix}/games/vegastrike/data/textures/supernova.bmp
%{prefix}/games/vegastrike/data/textures/pluto.bmp
%{prefix}/games/vegastrike/data/textures/TerranPriA128.bmp
%{prefix}/games/vegastrike/data/textures/beamtexture.bmp
%{prefix}/games/vegastrike/data/textures/KilrathiPriA.bmp
%{prefix}/games/vegastrike/data/textures/CommieSecA.bmp
%{prefix}/games/vegastrike/data/textures/Capskn3.bmp
%{prefix}/games/vegastrike/data/textures/beam.bmp
%{prefix}/games/vegastrike/data/textures/crosshairs.alp
%{prefix}/games/vegastrike/data/textures/crosshairs.bmp
%{prefix}/games/vegastrike/data/textures/TechSecRGB.bmp
%{prefix}/games/vegastrike/data/textures/saturn-ring.alp
%{prefix}/games/vegastrike/data/textures/saturn-ring.bmp
%{prefix}/games/vegastrike/data/textures/particle.bmp
%{prefix}/games/vegastrike/data/textures/venus.bmp
%{prefix}/games/vegastrike/data/textures/uranus.bmp
%{prefix}/games/vegastrike/data/textures/TechSecA.bmp
%{prefix}/games/vegastrike/data/textures/particlelong.bmp
%{prefix}/games/vegastrike/data/textures/TerranSecRGB.bmp
%{prefix}/games/vegastrike/data/textures/neutrongun.bmp
%{prefix}/games/vegastrike/data/textures/shield.bmp
%{prefix}/games/vegastrike/data/textures/CommieSecRGB.bmp
%{prefix}/games/vegastrike/data/textures/sun.bmp
%{prefix}/games/vegastrike/data/textures/hull1.bmp
%{prefix}/games/vegastrike/data/textures/hull2.bmp
%{prefix}/games/vegastrike/data/textures/moon.bmp
%{prefix}/games/vegastrike/data/textures/mars.bmp
%{prefix}/games/vegastrike/data/textures/Makefile.am
%{prefix}/games/vegastrike/data/textures/saturn.bmp
%{prefix}/games/vegastrike/data/textures/9x12.alp
%{prefix}/games/vegastrike/data/textures/9x12.bmp
%{prefix}/games/vegastrike/data/textures/TechPriA.bmp
%{prefix}/games/vegastrike/data/textures/neutrontexture.bmp
%{prefix}/games/vegastrike/data/textures/disruptorbeam.bmp
%{prefix}/games/vegastrike/data/textures/TechPriRGB.bmp
%{prefix}/games/vegastrike/data/textures/laserred.bmp
%{prefix}/games/vegastrike/data/textures/asymmetric.bmp
%{prefix}/games/vegastrike/data/textures/laser.bmp
%{prefix}/games/vegastrike/data/textures/TerranPriRGB.bmp
%{prefix}/games/vegastrike/data/textures/earth.bmp
%{prefix}/games/vegastrike/data/textures/meson.bmp
%{prefix}/games/vegastrike/data/textures/neptune.bmp
%{prefix}/games/vegastrike/data/textures/TerranSecA.bmp
%{prefix}/games/vegastrike/data/textures/Rapier.bmp
%{prefix}/games/vegastrike/data/textures/disruptor.bmp
%{prefix}/games/vegastrike/data/textures/bolt.bmp
%{prefix}/games/vegastrike/data/textures/ion.bmp
%{prefix}/games/vegastrike/data/textures/tachyon.bmp
%{prefix}/games/vegastrike/data/textures/jupiter.bmp
%{prefix}/games/vegastrike/data/textures/massdrivertexture.bmp
%{prefix}/games/vegastrike/data/.xvpics/eject.alp
%{prefix}/games/vegastrike/data/.xvpics/eject.bmp
%{prefix}/games/vegastrike/data/.xvpics/hornet-top.alp
%{prefix}/games/vegastrike/data/.xvpics/hornet-top.bmp
%{prefix}/games/vegastrike/data/.xvpics/selectbox.alp
%{prefix}/games/vegastrike/data/.xvpics/selectbox.bmp
%{prefix}/games/vegastrike/data/.xvpics/auto.alp
%{prefix}/games/vegastrike/data/.xvpics/auto.bmp
%{prefix}/games/vegastrike/data/.xvpics/crosshairs.alp
%{prefix}/games/vegastrike/data/.xvpics/blasterpower.alp
%{prefix}/games/vegastrike/data/.xvpics/blasterpower.bmp
%{prefix}/games/vegastrike/data/.xvpics/shieldf.alp
%{prefix}/games/vegastrike/data/.xvpics/shieldf.bmp
%{prefix}/games/vegastrike/data/.xvpics/hornet-cockpit.bmp
%{prefix}/games/vegastrike/data/.xvpics/hornet-cockpit.xcf
%{prefix}/games/vegastrike/data/.xvpics/armorf.bmp
%{prefix}/games/vegastrike/data/.xvpics/armorl.alp
%{prefix}/games/vegastrike/data/.xvpics/armorl.bmp
%{prefix}/games/vegastrike/data/.xvpics/locklight.alp
%{prefix}/games/vegastrike/data/.xvpics/locklight.bmp
%{prefix}/games/vegastrike/data/.xvpics/rapier-top.alp
%{prefix}/games/vegastrike/data/.xvpics/rapier-top.bmp
%{prefix}/games/vegastrike/data/.xvpics/hornet-cockpitalp.bmp
%{prefix}/games/vegastrike/data/.xvpics/fuelstat.alp
%{prefix}/games/vegastrike/data/.xvpics/fuelstat.bmp
%{prefix}/games/vegastrike/data/.xvpics/bolt.bmp
%{prefix}/games/vegastrike/data/.xvpics/radar.alp
%{prefix}/games/vegastrike/data/.xvpics/radar.bmp
%{prefix}/games/vegastrike/data/test4.mission
%{prefix}/games/vegastrike/data/Makefile.am
%{prefix}/games/vegastrike/data/Makefile.in
%{prefix}/games/vegastrike/data/cube_sphere.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/eject.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/eject.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/eject.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/auto.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/auto.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/auto.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/crosshairs.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/rvdu.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/blasterpower.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/blasterpower.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/blasterpower.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/Makefile.am
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/shieldf.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/shieldf.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/shieldf.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/hornet-cockpit.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/hornet-cockpit.cpt
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/hornet-cockpit.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/armorf.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/armorf.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/armorl.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/armorl.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/armorl.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/locklight.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/locklight.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/locklight.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/lvdu.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/hornet-cockpitalp.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/fuelstat.alp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/fuelstat.bmp
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/fuelstat.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/generic.spr
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/9x12.font
%{prefix}/games/vegastrike/data/hornet-cockpit.cpt/radar.spr
%{prefix}/games/vegastrike/data/9x12.alp
%{prefix}/games/vegastrike/data/meshes/Makefile.am
%{prefix}/games/vegastrike/data/tnt.config
%{prefix}/games/vegastrike/data/sounds/Gorgon.wav
%{prefix}/games/vegastrike/data/sounds/mass.wav
%{prefix}/games/vegastrike/data/sounds/engine_5.wav
%{prefix}/games/vegastrike/data/sounds/explosion.wav
%{prefix}/games/vegastrike/data/sounds/afterburner.wav
%{prefix}/games/vegastrike/data/sounds/beam.wav
%{prefix}/games/vegastrike/data/sounds/Laser.wav
%{prefix}/games/vegastrike/data/sounds/EXPLOSIONPROMISING.wav
%{prefix}/games/vegastrike/data/sounds/electricity.wav
%{prefix}/games/vegastrike/data/sounds/missile_3.wav
%{prefix}/games/vegastrike/data/sounds/armorhit.wav
%{prefix}/games/vegastrike/data/sounds/Makefile.am
%{prefix}/games/vegastrike/data/sounds/shieldhit.wav
%{prefix}/games/vegastrike/data/sounds/Tachyon.wav
%{prefix}/games/vegastrike/data/sounds/Flux.wav
%{prefix}/games/vegastrike/data/sounds/shieldhit2.wav
%{prefix}/games/vegastrike/data/sounds/ion.wav
%{prefix}/games/vegastrike/data/sounds/Particle.wav
%{prefix}/games/vegastrike/data/sounds/sfx07c.wav
%{prefix}/games/vegastrike/data/sounds/Neutron.wav
%{prefix}/games/vegastrike/data/factions.xml
%{prefix}/games/vegastrike/data/expat.dll
%{prefix}/games/vegastrike/data/red05_light.bmp
%{prefix}/games/vegastrike/data/vegastrike.config
%{prefix}/games/vegastrike/data/weapon_list.xml
%{prefix}/games/vegastrike/data/test1.mission
%{prefix}/games/vegastrike/data/peace.m3u
%{prefix}/games/vegastrike/data/geforce3.config
%{prefix}/games/vegastrike/data/cube_light.bmp
%{prefix}/games/vegastrike/data/bolt.wav
%{prefix}/games/vegastrike/data/testworks.xml
%{prefix}/games/vegastrike/data/test3.mission
%{prefix}/games/vegastrike/data/9x12.font
%{prefix}/games/vegastrike/data/battle.m3u
%{prefix}/games/vegastrike/data/voodoo.config
%{prefix}/games/vegastrike/data/software.config
%{prefix}/games/vegastrike/data/vs1000.exe
%{prefix}/games/vegastrike/data/OpenAL32.dll
%{prefix}/games/vegastrike/data/SDL.dll
%{prefix}/games/vegastrike/data/install.PIF
%{prefix}/games/vegastrike/data/GM2.txt
%{prefix}/games/vegastrike/data/stdout.txt
%{prefix}/games/vegastrike/data/choice.com
%{prefix}/games/vegastrike/data/voodoo.config.ns
%{prefix}/games/vegastrike/data/tnt.config.ns
%{prefix}/games/vegastrike/data/software.config.ns
%{prefix}/games/vegastrike/data/geforce3.config.ns
%{prefix}/games/vegastrike/data/geforce2.config.ns
%{prefix}/games/vegastrike/data/vs200.exe
%{prefix}/games/vegastrike/data/stderr.txt
%{prefix}/games/vegastrike/data/VegastrikeMission2.bat
%{prefix}/games/vegastrike/data/VegastrikeMission3.bat
%{prefix}/games/vegastrike/data/VegastrikeMission4.bat
%{prefix}/games/vegastrike/data/VegastrikeMission5.bat
