#!/bin/bash
#====================================
# @file   : build
# @brief  : build vsUTCS
# @usage  : script/build
# @param  : none
#====================================

#============ DESCRIPTION ===========
# The steps for creating this script were adapted from:
# https://github.com/Taose/Vegastrike-taose/wiki/How-to-Build
#====================================

# Copyright (C) 2020-2022 Stephen G. Tuggy and other vsUTCS contributors
#
# This file is part of Vega Strike: Upon the Coldest Sea ("vsUTCS").
#
# vsUTCS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# vsUTCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsUTCS.  If not, see <https://www.gnu.org/licenses/>.


set -e

echo "--------------------------"
echo "--- build | 2022-01-23 ---"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
BUILD_DIR="${ROOT_DIR}/build"
BIN_DIR="${ROOT_DIR}/bin"
SRC_DIR="${ROOT_DIR}/engine"
COMMAND=""

echo "ROOT_DIR: ${ROOT_DIR}"
echo "BUILD_DIR: ${BUILD_DIR}"

# -p creates if the target doesn't exist, noop otherwise
mkdir -pv "${BUILD_DIR}" && cd "${BUILD_DIR}"

cmake $@ "${SRC_DIR}"

# for a clean build only
# mut we can do it manually
#make clean

# compile now using all cpus and show compilation commands
# MAX_THREADS_TO_BUILD_WITH=8
NUM_THREADS_TO_BUILD_WITH=$(getconf _NPROCESSORS_ONLN)
# if [ ${NUM_THREADS_TO_BUILD_WITH} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
# then
#     NUM_THREADS_TO_BUILD_WITH=${MAX_THREADS_TO_BUILD_WITH}
# fi

VERBOSE=1 cmake --build "${BUILD_DIR}" -j $NUM_THREADS_TO_BUILD_WITH

cd "${ROOT_DIR}"
