#!/bin/bash
#====================================
# @file   : build
# @brief  : build vsUTCS
# @usage  : script/build
# @param  : none
#====================================

#============ DESCRIPTION ===========
# The steps for creating this script were adapted from:
# https://github.com/Taose/Vegastrike-taose/wiki/How-to-Build
#====================================

# Copyright (C) 2020 Stephen G. Tuggy and other vsUTCS contributors
#
# This file is part of Vega Strike: Upon the Coldest Sea ("vsUTCS").
#
# vsUTCS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# vsUTCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsUTCS.  If not, see <https://www.gnu.org/licenses/>.


set -e

echo "--------------------------"
echo "--- build | 2025-01-13 ---"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
BUILD_DIR=$ROOT_DIR/build
SRC_DIR=$ROOT_DIR
COMMAND=""

# -p creates if the target doesn't exist, noop otherwise
mkdir -pv "$BUILD_DIR" && cd "$BUILD_DIR"

cmake $@ "$SRC_DIR"

cmake --build "$BUILD_DIR"

cd "$ROOT_DIR"
