#!/bin/bash
#====================================
# @file   : cibuild
# @brief  : Builds vsUTCS for purposes of CI/CD (Travis)
# @usage  : script/cibuild
# @param  : none
#====================================
# Copyright (C) 2020 Stephen G. Tuggy and other vsUTCS contributors
#
# This file is part of Vega Strike: Upon the Coldest Sea ("vsUTCS").
#
# vsUTCS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# vsUTCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsUTCS.  If not, see <https://www.gnu.org/licenses/>.


set -e

if [ "$TRAVIS_OS_NAME" == "linux" ]
then
    SRC_DOCKER_IMG_NAME="vegastrike/vega-strike-build-env:$(echo $FROM | sed 's/:/_/' | sed 's/\//_/')"
    DST_DOCKER_IMG_NAME="building-vsutcs:$(echo $FROM | sed 's/:/_/' | sed 's/\//_/')"
    DOCKER_CONTAINER_NAME="building-vsutcs_$(echo $FROM | sed 's/:/_/' | sed 's/\//_/')"
    docker build --build-arg from=$SRC_DOCKER_IMG_NAME -t $DST_DOCKER_IMG_NAME .
    docker run --env TRAVIS_TAG=$TRAVIS_TAG --name $DOCKER_CONTAINER_NAME $DST_DOCKER_IMG_NAME
    if ! [ -z "$TRAVIS_TAG" ]
    then
        docker cp $DOCKER_CONTAINER_NAME:/usr/src/vsUTCS/packages .
    fi
    docker rm $DOCKER_CONTAINER_NAME
else
    script/docker-entrypoint.sh $@
fi

echo "cibuild Done!"
