name: 'MacOS-CI'
permissions:
    contents: read
    pull-requests: read

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os:
          # x86-64
          - macos-15-intel
          # M1 processor
          #- macos-14
          #- macos-15

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      - name: Build it
        env:
          IS_RELEASE: 0
        run: script/cibuild $FLAGS
