name: Windows-CI
permissions:
    contents: read
    pull-requests: read

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2022
            is-release:      0
          - os:              windows-2025
            is-release:      0

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install CMake
        uses: lukka/get-cmake@7bfc9baacbbdcb5e37957ad05c3546b3e222be3c #v4.3.2

      - name: Build it
        run: script/build.ps1
