name: Windows-Release
permissions:
    contents: write
    pull-requests: read

# Controls when the action will run.
on:
  release:
    types:
      - created
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2022
            is-release:      1
            install-nsis:    0
          - os:              windows-2025
            is-release:      1
            install-nsis:    1

    env:
      TAG_NAME: '${{ github.ref_name }}'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9.0.0
        with:
          script: |
            const git_sha = context.sha.substring(0, 7)
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('SHORT_SHA', git_sha);

      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install CMake
        uses: lukka/get-cmake@f5b8fbb4d77cec1acc5a5f9f0df4beffaf5d98d9 #v4.3.4

      - name: Install NSIS
        if: ${{ matrix.install-nsis }}
        uses: repolevedavaj/install-nsis@1ab2f7ba2fe9408db612029be0bb3c0088b0d3e9 # v1.2.1
        with:
          nsis-version: '3.12'

      - name: Build the code
        run: script/build.ps1

      - name: Package the code
        run: script/package.ps1

      - name: Upload the artifacts
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.*"
